"""
Base class for IDF generators.
Provides common functionality shared by IDFGenerator and ProfessionalIDFGenerator.
"""
from datetime import datetime
from typing import Set, Optional


class BaseIDFGenerator:
    """Base class for IDF generators with common functionality."""
    
    def __init__(self, version: str = "25.1"):
        """
        Initialize base IDF generator.
        
        Args:
            version: EnergyPlus version string
        """
        self.version = version
        self.unique_names: Set[str] = set()
    
    def _generate_unique_name(self, base_name: str) -> str:
        """
        Generate a unique object name in the IDF.
        
        Args:
            base_name: Base name for the object
            
        Returns:
            Unique name (base_name if available, otherwise base_name_N)
        """
        if base_name not in self.unique_names:
            self.unique_names.add(base_name)
            return base_name
        
        counter = 1
        while f"{base_name}_{counter}" in self.unique_names:
            counter += 1
        
        unique_name = f"{base_name}_{counter}"
        self.unique_names.add(unique_name)
        return unique_name
    
    def reset_unique_names(self) -> None:
        """Reset the unique names set (useful for generating multiple IDFs)."""
        self.unique_names.clear()
    
    def generate_header(self, generator_name: str = "IDF Creator") -> str:
        """
        Generate IDF file header.
        
        Args:
            generator_name: Name of the generator tool
            
        Returns:
            Header string for IDF file
        """
        return f"""! EnergyPlus IDF File
! Generated by {generator_name}
! Version: {self.version}
! Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

"""
    
    def generate_version_section(self) -> str:
        """
        Generate Version section.
        
        Returns:
            Version section string
        """
        return f"""Version,
  {self.version};                    !- Version Identifier

"""
    
    def _format_comment(self, text: str) -> str:
        """
        Format a comment line.
        
        Args:
            text: Comment text
            
        Returns:
            Formatted comment string
        """
        return f"  !- {text}"
    
    def _format_field(self, value: Optional[str], comment: Optional[str] = None) -> str:
        """
        Format an IDF field with optional comment.
        
        Args:
            value: Field value
            comment: Optional comment
            
        Returns:
            Formatted field string
        """
        if comment:
            return f"  {value},{self._format_comment(comment)}"
        return f"  {value},"

